### PR TITLE
ci(Mergify): configuration update

### PR DESCRIPTION
**Pull request by ertugrulphp**
This change has been made by @ertugrulphp from Mergify config editor.

### CODE REVIEW

**Comment by ghost** [comment]
@Mergifyio unqueue

**Comment by ertugrulphp** [comment]
@Mergifyio rebase

**Comment by ghost** [comment]
@Mergifyio copy main">

**Comment by ertugrulphp** [comment]
@Mergifyio copy main">

**Comment by ertugrulphp** [comment]
hghghg

**Comment by ghost** [comment]
testyttt

**Comment by ghost** [comment]
@Mergifyio copy main">

**Comment by ertugrulphp** [comment]
@Mergifyio refresh

**Comment by ertugrulphp** [comment]
@Mergifyio unqueue

**Comment by ghost** [comment]
https://github.com/Mergifyio unqueue

**Pull request merged**
